### PR TITLE
Tenants options pattern

### LINKED ISSUE #146: Replace Tenants with TenantOptions
Currently the tenants are loaded from the configuration and then immediately all values are validated.  This is happening in `Elders.Cronus.Multitenancy.Tenants`. 

Dotnet core provides a good abstraction for loading and validating values with its Options pattern.

The suggestion here is to rework the Tenants class using options pattern.

### PR DESCRIPTION
**Pull request by ethno2405**
# Title
Use Options pattern to inject tenants

## Related Issue 
Closes #146 

### Description
We are now relying on the application to provide a list of tenants instead of a single string that Cronus parses. The tenants are being checked for invalid characters during initialization and every time the configuration changes. An `ArgumentException` will thrown in case of invalid tenant value.

### Test Methods
Changing the tenant list with valid tenants should result in replacing the old list with the new one.
Changing the tenant list with an empty one should result in exception and the old values should remain.

### CODE REVIEW

**Comment by ethno2405** [comment]
What should happen here https://github.com/Elders/Cronus/blob/release-6.0.0/src/Elders.Cronus/MessageProcessing/CronusContextFactory.cs when the tenants change?

**Comment by mynkow** [comment]
The tenant options must be registered during .AddCronus() like:  
`services.AddOptions<TenantOptions,TenantOptionsProvider>()`

Here is an example of such provider: https://github.com/Elders/Cronus.Projections.Cassandra/blob/159f7c012e86bef6acc0b9711261c3de11f50827/src/Elders.Cronus.Projections.Cassandra/Infrastructure/CassandraProviderOptionsProvider.cs

**Comment by mynkow** [comment]
To get the value from the options monitor you could use `monitor.CurrentValue` instead of doing it by key because the key will be already supplied by the provider (see prev. comment)

**Comment by mynkow** [comment]
@ethno2405 I had to try this and it seems that it is possible to completely replace ITenantList with TenantsOptions using the options pattern. Now we just need to test the tenant validation class. Everything else related to the infrastructure such as loading and reloading tenants from the configuration is dotnet core related.

**Comment by mynkow** [comment]
This PR opens the doors for #145 and we can finalize it

**Pull request merged**
